spring:
  datasource:
    platform: postgress
    initialization-mode: always
    master:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/Database1
      username: postgres
      password: baseball
    replica:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/Database2
      username: postgres
      password: baseball
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    